# NETFLIX EDA - Movies and TV Shows

In [ ]:
# Libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
FILE_PATH = "/home/gustavo/repos/netflix-eda/data/raw/netflix_data.csv"

df = pd.read_csv(FILE_PATH)

## Etapa 1 - Entendimiento del dataset

In [4]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,1,A genetics professor experiments with a treatm...,International TV

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   str
 1   type          4812 non-null   str
 2   title         4812 non-null   str
 3   director      4812 non-null   str
 4   cast          4812 non-null   str
 5   country       4812 non-null   str
 6   date_added    4812 non-null   str
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   str
 10  genre         4812 non-null   str
dtypes: int64(2), str(9)
memory usage: 413.7 KB

In [7]:
df.shape

(4812, 11)

In [ ]:
# NaN values?

df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
duration        0
description     0
genre           0
dtype: int64

In [ ]:
# null values?

df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
duration        0
description     0
genre           0
dtype: int64

## ETAPA 2 — Limpieza de datos

In [ ]:
# Identificar si existen valores duplicados

df.duplicated().sum()

np.int64(0)

In [20]:
# Transformar la columan date_added

df['date_added'] = pd.to_datetime(df['date_added'], format='mixed', errors='coerce')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   str
 1   type          4812 non-null   str
 2   title         4812 non-null   str
 3   director      4812 non-null   str
 4   cast          4812 non-null   str
 5   country       4812 non-null   str
 6   date_added    4812 non-null   datetime64[us]
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   str
 10  genre         4812 non-null   str
dtypes: datetime64[us](1), int64(2), str(8)
memory usage: 413.7 KB

In [22]:
# Crear columna para año y mes del dataset

df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,year_added,month_added
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016-12-23,2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,2016,12
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2018-12-20,2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,2018,12

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   str
 1   type          4812 non-null   str
 2   title         4812 non-null   str
 3   director      4812 non-null   str
 4   cast          4812 non-null   str
 5   country       4812 non-null   str
 6   date_added    4812 non-null   datetime64[us]
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   str
 10  genre         4812 non-null   str
 11  year_added    4812 non-null   int32
 12  month_added   4812 non-null   int32
dtypes: datetime64[us](1), int32(2), int64(2), str(8)
memory usage: 451.3 KB

In [42]:
# Verificación columna 'type'

df['type'].unique()

<StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str

In [50]:
# Verificación columna 'release_year'
df['release_year'].unique()

array([2016, 2011, 2009, 2008, 2019, 1997, 2017, 2018, 2014, 2020, 2015,
       2010, 2005, 2012, 2006, 2013, 2000, 1989, 2004, 1977, 1971, 1993,
       2007, 1998, 1988, 1996, 2002, 1986, 1990, 1979, 1980, 1974, 2001,
       1999, 1966, 1991, 1982, 1994, 2003, 1995, 1978, 1992, 1972, 1975,
       1973, 1967, 1960, 1981, 1958, 1976, 2021, 1968, 1956, 1985, 1965,
       1984, 1983, 1987, 1945, 1946, 1962, 1969, 1955, 1963, 1964, 1942,
       1954, 1970, 1947, 1944, 1959])

In [66]:
print(df['duration'].max())
print(df['duration'].min())
print(df['duration'].mean())

253
1
99.56670822942644

In [65]:
df[df['duration'] == 1].value_counts().sum()

np.int64(97)

In [ ]:
# Verificación columna 'country'

countries = df['country'].unique()
countries = countries.tolist()
countries.sort()
print(countries)

['Argentina', 'Australia', 'Austria', 'Bangladesh', 'Belgium', 'Brazil', 'Bulgaria', 'Cambodia', 'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Czech Republic', 'Denmark', 'Egypt', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Guatemala', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Kenya', 'Kuwait', 'Lebanon', 'Malaysia', 'Mexico', 'Namibia', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Pakistan', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia', 'Serbia', 'Singapore', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Soviet Union', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'United Arab', 'United Kingdom', 'United States', 'Uruguay', 'Venezuela', 'Vietnam', 'Zimbabwe']